### ISSUE TITLE
Invalid type passed to Navigator.of(...).pop()

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync-app#159]
On commit 3afa735741c1f4e98463456918071fce173a977b

```
E/flutter ( 8840): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'bool?' of 'result'
E/flutter ( 8840): #0      LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart)
E/flutter ( 8840): #1      _RouteEntry.handlePop (package:flutter/src/widgets/navigator.dart:2900:16)
E/flutter ( 8840): #2      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3892:22)
E/flutter ( 8840): #3      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:4967:7)
E/flutter ( 8840): #4      _AddRepositoryWithTokenState._onSaved (package:ouisync_app/app/widgets/dialogs/modal_add_repo_token_dialog.dart:392:34)
E/flutter ( 8840): <asynchronous suspension>
```

**Comment by IvanaBlzvc** [comment]
@J-Pabon Jorge, can you please see if this needs to remain open?  Or is it maybe already solved an can be closed?

**Comment by IvanaBlzvc** [comment]
As per confirmation in MM (21/02/23) by Jorge, closing
