### ISSUE TITLE
Xiaomi device - when battery optimisation is disabled the app becomes unresponsive

### ISSUE THREAD

**Issue by IvanaBlzvc** [equalitie/ouisync-app#275]
When app is installed on Xiaomi device, user is asked to disable the battery optimisation - see the attached screen
![screenshot-1692097875223](https://github.com/equalitie/ouisync-app/assets/121942562/3d48fc7f-88f5-4c86-8857-1cde5e39ede4)
Then the user is redirected to this screen
![screenshot-1692097886723](https://github.com/equalitie/ouisync-app/assets/121942562/54465f77-5330-4cd1-ad84-e07742b03937)
If the user doesn't change any settings here but leave the recommended battery saver settings, then they get this message 
![screenshot-1692097116464](https://github.com/equalitie/ouisync-app/assets/121942562/075a076f-e79b-4742-a500-fd1cb934780e)
But if they do select teh No restrictions (which is optimal for syncing purposes) then the app freezes/becomes unresponsive and the user has to restart it.  After restart it seems to run OK and the batter optimisation seems to be OFF as well.  
![screenshot-1692098533002](https://github.com/equalitie/ouisync-app/assets/121942562/32e42a34-d7f9-48ce-bd52-1bec20a98158)

**Comment by IvanaBlzvc** [comment]
"don't keep activities" = OFF

**Comment by IvanaBlzvc** [comment]
If I run a dev version (1993c4b0) in release mode then the app doesn't seem to become unresponsive after selecting the 'no restriction' option.  To retest this with the new RC as and when available.

**Comment by IvanaBlzvc** [comment]
A logcat - for future investigations if needed
[log_file.txt](https://github.com/equalitie/ouisync-app/files/12427944/log_file.txt)
Start of relevant info
java.lang.ClassNotFoundException: miui.security.appcompatibility.AppCompatibilityManager
08-24 11:33:48.127 28852 24386 E AppCompatManager: 	at java.lang.Class.classForName(Native Method)
08-24 11:33:48.127 28852 24386 E AppCompatManager: 	at java.lang.Class.forName(Class.java:454)
08-24 11:33:48.127 28852 24386 E AppCompatManager: 	at java.lang.Class.forName(Class.java:379)
08-24 11:33:48.127 28852 24386 E AppCompatManager: 	at com.miui.appcompatibility.b.c(Unknown Source:2)
08-24 11:33:48.127 28852 24386 E AppCompatManager: 	at com.miui.appcompatibility.b.a(Unknown Source:29)
08-24 11:33:48.127 28852 24386 E AppCompatManager: 	at com.miui.appcompatibility.b.a(Unknown Source:4)
08-24 11:33:48.127 28852 24386 E AppCompatManager: 	at com.miui.appcompatibility.g.a$a.a(Unknown Source:12)
08-24 11:33:48.127 28852 24386 E AppCompatManager: 	at com.miui.appcompatibility.g.a$a.doInBackground(Unknown Source:2)
08-24 11:33:48.127 28852 24386 E AppCompatManager: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
08-24 11:33:48.127 28852 24386 E AppCompatManager: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-24 11:33:48.127 28852 24386 E AppCompatManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-24 11:33:48.127 28852 24386 E AppCompatManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-24 11:33:48.127 28852 24386 E AppCompatManager: 	at java.lang.Thread.run(Thread.java:923)
08-24 11:33:48.127 28852 24386 E AppCompatManager: Caused by: java.lang.ClassNotFoundException: miui.security.appcompatibility.AppCompatibilityManager
08-24 11:33:48.127 28852 24386 E AppCompatManager: 	... 13 more

**Comment by IvanaBlzvc** [comment]
retested with 0.7.8 = OK
