### ISSUE TITLE
Adding file via the FAB  doesn't work on linux

### ISSUE THREAD

**Issue by madadam** [equalitie/ouisync-app#289]
It throws an exception:
```
Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      MethodChannelPermissionHandler.requestPermissions (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:71:9)
<asynchronous suspension>
#2      PermissionActions.request (package:permission_handler/permission_handler.dart:44:31)
<asynchronous suspension>
#3      Permissions.requestPermission (package:ouisync_app/app/utils/permissions.dart:11:9)
<asynchronous suspension>
#4      DirectoryActions._checkPermission (package:ouisync_app/app/widgets/dialogs/modal_actions_bottom_sheet.dart:170:20)
<asynchronous suspension>
#5      DirectoryActions.addFile (package:ouisync_app/app/widgets/dialogs/modal_actions_bottom_sheet.dart:91:9)
<asynchronous suspension>
#6      DirectoryActions.build.<anonymous closure> (package:ouisync_app/app/widgets/dialogs/modal_actions_bottom_sheet.dart:45:41)
<asynchronous suspension>
 :: app{scope="Global Loggy"} :: ffi/src/lib.rs:250
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      MethodChannelPermissionHandler.requestPermissions (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:71:9)
<asynchronous suspension>
#2      PermissionActions.request (package:permission_handler/permission_handler.dart:44:31)
<asynchronous suspension>
#3      Permissions.requestPermission (package:ouisync_app/app/utils/permissions.dart:11:9)
<asynchronous suspension>
#4      DirectoryActions._checkPermission (package:ouisync_app/app/widgets/dialogs/modal_actions_bottom_sheet.dart:170:20)
<asynchronous suspension>
#5      DirectoryActions.addFile (package:ouisync_app/app/widgets/dialogs/modal_actions_bottom_sheet.dart:91:9)
<asynchronous suspension>
#6      DirectoryActions.build.<anonymous closure> (package:ouisync_app/app/widgets/dialogs/modal_actions_bottom_sheet.dart:45:41)
<asynchronous suspension>
```

EDIT: It does work via drag&drop.

**Comment by J-Pabon** [comment]
Same as #297
