### ISSUE TITLE
Showing the external IP address doesn't work on linux

### ISSUE THREAD

**Issue by madadam** [equalitie/ouisync-app#290]
Linux is not supported by the underlying [plugin](https://pub.dev/packages/r_get_ip):

```
Unhandled Exception: MissingPluginException(No implementation found for method getExternalIP on channel r_get_ip)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      RGetIp.externalIP (package:r_get_ip/r_get_ip.dart:25:26)
<asynchronous suspension>
#2      ConnectivityInfo.update (package:ouisync_app/app/cubits/connectivity_info.dart:155:26)
<asynchronous suspension>
 :: app{scope="Global Loggy"} :: ffi/src/lib.rs:250
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getExternalIP on channel r_get_ip)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      RGetIp.externalIP (package:r_get_ip/r_get_ip.dart:25:26)
<asynchronous suspension>
#2      ConnectivityInfo.update (package:ouisync_app/app/cubits/connectivity_info.dart:155:26)
<asynchronous suspension>
```

**Comment by IvanaBlzvc** [comment]
tested with 0.7.5 = OK
