### ISSUE TITLE
Downloading files from ouisync to the local filesystem doesn't work on linux

### ISSUE THREAD

**Issue by madadam** [equalitie/ouisync-app#365]
It throws this error:

```
Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
<asynchronous suspension>
#1      MethodChannelPermissionHandler.requestPermissions (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:79:9)
<asynchronous suspension>
#2      PermissionActions.request (package:permission_handler/permission_handler.dart:109:10)
<asynchronous suspension>
#3      FuturePermissionStatusGetters.isGranted (package:permission_handler_platform_interface/src/permission_status.dart:110:40)
<asynchronous suspension>
#4      _SaveToDeviceState._downloadFile (package:ouisync_app/app/widgets/dialogs/modal_save_to_device_bottom_sheet.dart:85:9)
<asynchronous suspension>
#5      _SaveToDeviceState._actions.<anonymous closure> (package:ouisync_app/app/widgets/dialogs/modal_save_to_device_bottom_sheet.dart:78:15)
<asynchronous suspension>
 :: app{scope="Global Loggy"} :: ffi/src/lib.rs:237
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
<asynchronous suspension>
#1      MethodChannelPermissionHandler.requestPermissions (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:79:9)
<asynchronous suspension>
#2      PermissionActions.request (package:permission_handler/permission_handler.dart:109:10)
<asynchronous suspension>
#3      FuturePermissionStatusGetters.isGranted (package:permission_handler_platform_interface/src/permission_status.dart:110:40)
<asynchronous suspension>
#4      _SaveToDeviceState._downloadFile (package:ouisync_app/app/widgets/dialogs/modal_save_to_device_bottom_sheet.dart:85:9)
<asynchronous suspension>
#5      _SaveToDeviceState._actions.<anonymous closure> (package:ouisync_app/app/widgets/dialogs/modal_save_to_device_bottom_sheet.dart:78:15)
<asynchronous suspension>
```

**Comment by madadam** [comment]
Fixed in https://github.com/equalitie/ouisync-app/commit/d931eb8434febcd95c0b82d1f04f9d5f698953b2
